version: '3.8'

services:
  totem:
    build: .
    networks:
      - default
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - /app/node_modules

networks:
  default:
    driver: bridge
